import { ExamRecord, CompletedExamRecord } from "./types";

export const initialExamsList: ExamRecord[] = [
  {
    id: "e1",
    examName: "National Science Olympiad (NSO)",
    examCode: "NSO25",
    classes: "IX, X",
    examDate: "18 Aug 2025",
    schedule: "09:00 AM - 11:00 AM",
    duration: "2 hrs",
    registrationEnds: "10 Aug 2025",
    daysLeft: "2 days left",
    status: "Open",
  },
  {
    id: "e2",
    examName: "IMO Mathematics Olympiad",
    examCode: "IMO25",
    classes: "VIII, IX",
    examDate: "22 Aug 2025",
    schedule: "01:00 PM - 03:00 PM",
    duration: "2 hrs",
    registrationEnds: "15 Aug 2025",
    daysLeft: "7 days left",
    status: "Open",
  },
  {
    id: "e3",
    examName: "Cyber Olympiad",
    examCode: "CYBER25",
    classes: "IX, X",
    examDate: "30 Aug 2025",
    schedule: "03:30 PM - 05:00 PM",
    duration: "90 mins",
    registrationEnds: "20 Aug 2025",
    daysLeft: "12 days left",
    status: "Open",
  },
  {
    id: "e4",
    examName: "English Olympiad",
    examCode: "ENG25",
    classes: "VII, VIII",
    examDate: "05 Sep 2025",
    schedule: "09:00 AM - 10:00 AM",
    duration: "1 hr",
    registrationEnds: "25 Aug 2025",
    daysLeft: "17 days left",
    status: "Open",
  },
  {
    id: "e5",
    examName: "AI Olympiad",
    examCode: "AI25",
    classes: "IX, X",
    examDate: "12 Sep 2025",
    schedule: "02:00 PM - 04:00 PM",
    duration: "2 hrs",
    registrationEnds: "01 Sep 2025",
    daysLeft: "24 days left",
    status: "Upcoming",
  },
  {
    id: "e6",
    examName: "Drawing Olympiad",
    examCode: "ART25",
    classes: "IV - VIII",
    examDate: "20 Sep 2025",
    schedule: "10:00 AM - 11:30 AM",
    duration: "1.5 hrs",
    registrationEnds: "10 Sep 2025",
    daysLeft: "31 days left",
    status: "Upcoming",
  },
  {
    id: "e7",
    examName: "GK Olympiad",
    examCode: "GKO25",
    classes: "II - X",
    examDate: "28 Sep 2025",
    schedule: "09:00 AM - 10:00 AM",
    duration: "1 hr",
    registrationEnds: "18 Sep 2025",
    daysLeft: "41 days left",
    status: "Upcoming",
  },
  {
    id: "e8",
    examName: "Maths Talent Hunt",
    examCode: "MTH25",
    classes: "VI - X",
    examDate: "05 Oct 2025",
    schedule: "01:00 PM - 03:00 PM",
    duration: "2 hrs",
    registrationEnds: "25 Sep 2025",
    daysLeft: "48 days left",
    status: "Upcoming",
  },
];

export const initialCompletedExamsList: CompletedExamRecord[] = [
  {
    id: "com1",
    badgeText: "NSO",
    badgeBg: "bg-blue-600 text-white",
    examName: "National Science Olympiad (NSO)",
    subtitle: "Science talent search exam",
    code: "NSO24",
    classes: "I - XII",
    category: "Science",
    categoryBg: "bg-emerald-100/80 text-emerald-700",
    examDate: "10 May 2025",
    schedule: "09:00 AM - 11:00 AM",
    duration: "2 hrs",
    completedOn: "10 May 2025",
    totalParticipants: 214,
    status: "Completed",
  },
  {
    id: "com2",
    badgeText: "IMO",
    badgeBg: "bg-[#6B46C1] text-white",
    examName: "IMO Mathematics Olympiad",
    subtitle: "Mathematics competition",
    code: "IMO24",
    classes: "I - XII",
    category: "Mathematics",
    categoryBg: "bg-blue-100/80 text-blue-700",
    examDate: "08 May 2025",
    schedule: "01:00 PM - 03:00 PM",
    duration: "2 hrs",
    completedOn: "08 May 2025",
    totalParticipants: 186,
    status: "Completed",
  },
  {
    id: "com3",
    badgeText: "IEO",
    badgeBg: "bg-amber-500 text-white",
    examName: "International English Olympiad",
    subtitle: "English language proficiency exam",
    code: "IEO24",
    classes: "I - XII",
    category: "English",
    categoryBg: "bg-amber-100/80 text-amber-700",
    examDate: "05 May 2025",
    schedule: "10:00 AM - 11:30 AM",
    duration: "1.5 hrs",
    completedOn: "05 May 2025",
    totalParticipants: 198,
    status: "Completed",
  },
  {
    id: "com4",
    badgeText: "GK",
    badgeBg: "bg-emerald-600 text-white",
    examName: "International General Knowledge Olympiad",
    subtitle: "General knowledge assessment",
    code: "IGKO24",
    classes: "III - XII",
    category: "General Knowledge",
    categoryBg: "bg-purple-100/80 text-purple-700",
    examDate: "30 Apr 2025",
    schedule: "10:00 AM - 11:30 AM",
    duration: "1.5 hrs",
    completedOn: "30 Apr 2025",
    totalParticipants: 162,
    status: "Completed",
  },
  {
    id: "com5",
    badgeText: "NCO",
    badgeBg: "bg-red-500 text-white",
    examName: "National Cyber Olympiad",
    subtitle: "Cybersecurity knowledge test",
    code: "NCO24",
    classes: "VI - XII",
    category: "Cyber Security",
    categoryBg: "bg-sky-100/80 text-sky-700",
    examDate: "25 Apr 2025",
    schedule: "01:00 PM - 03:00 PM",
    duration: "2 hrs",
    completedOn: "25 Apr 2025",
    totalParticipants: 148,
    status: "Completed",
  },
];
