import {
  SchoolProfile,
  StatMetric,
  SubjectMetric,
  RegistrationStatus,
  ActivityItem,
  UpcomingExam,
} from "../_types/dashboard";

export const mockSchoolProfile: SchoolProfile = {
  name: "The Green Valley public school",
  welcomeMessage: "Welcome back, School Administrator!",
  adminName: "Admin",
  academicYears: ["2025 - 2026", "2024 - 2025", "2023 - 2024"],
  currentAcademicYear: "2025 - 2026",
  unreadNotifications: 1,
};

export const mockStatMetrics: StatMetric[] = [
  {
    id: "total-students",
    label: "Total Students",
    value: "1,842",
    subtitle: "Active students",
    subtitleColor: "text-emerald-600 font-medium",
    iconName: "users",
    iconBgColor: "bg-purple-100/70",
    iconColor: "text-purple-600",
  },
  {
    id: "registered-students",
    label: "Registered Students",
    value: "1,792",
    subtitle: "88% registered",
    subtitleColor: "text-emerald-600 font-medium",
    iconName: "check-square",
    iconBgColor: "bg-emerald-100/70",
    iconColor: "text-emerald-600",
  },
  {
    id: "pending-registrations",
    label: "Pending Registrations",
    value: "221",
    subtitle: "Need attention",
    subtitleColor: "text-amber-600 font-medium",
    iconName: "clock",
    iconBgColor: "bg-amber-100/70",
    iconColor: "text-amber-600",
  },
  {
    id: "upcoming-exams",
    label: "Upcoming Exams",
    value: "4",
    subtitle: "In next 30 days",
    subtitleColor: "text-purple-600 font-medium",
    iconName: "calendar",
    iconBgColor: "bg-purple-100/70",
    iconColor: "text-purple-600",
  },
  {
    id: "exams-completed",
    label: "Exams Completed",
    value: "28",
    subtitle: "Results published",
    subtitleColor: "text-emerald-600 font-medium",
    iconName: "check-circle",
    iconBgColor: "bg-emerald-100/70",
    iconColor: "text-emerald-600",
  },
];

export const mockSubjectMetrics: SubjectMetric[] = [
  {
    id: "math",
    name: "Mathematics",
    iconName: "sigma",
    iconBgColor: "bg-purple-100/80",
    iconColor: "text-purple-600",
    borderColor: "border-purple-200/80",
    avgScore: "84.5%",
    passRate: "92%",
    studentCount: 184,
  },
  {
    id: "science",
    name: "Science",
    iconName: "flask",
    iconBgColor: "bg-emerald-100/80",
    iconColor: "text-emerald-600",
    borderColor: "border-emerald-200/80",
    avgScore: "81.2%",
    passRate: "89%",
    studentCount: 184,
  },
  {
    id: "english",
    name: "English",
    iconName: "book",
    iconBgColor: "bg-purple-100/80",
    iconColor: "text-purple-600",
    borderColor: "border-purple-200/80",
    avgScore: "78.6%",
    passRate: "86%",
    studentCount: 184,
  },
];

export const mockRegistrationStatus: RegistrationStatus = {
  registeredCount: 1621,
  registeredPercentage: 88,
  pendingCount: 221,
  pendingPercentage: 12,
  rejectedCount: 34,
  rejectedPercentage: 2,
  totalStudents: 1842,
};

export const mockActivityLogs: ActivityItem[] = [
  {
    id: "act-1",
    title: "New student registered",
    timestamp: "10 min ago",
    type: "student",
    iconBgColor: "bg-purple-100",
    iconColor: "text-purple-600",
  },
  {
    id: "act-2",
    title: "Registration approved for National Science Olympiad",
    timestamp: "35 min ago",
    type: "approval",
    iconBgColor: "bg-emerald-100",
    iconColor: "text-emerald-600",
  },
  {
    id: "act-3",
    title: "Mathematics Olympiad created",
    timestamp: "1 hr ago",
    type: "creation",
    iconBgColor: "bg-purple-100",
    iconColor: "text-purple-600",
  },
  {
    id: "act-4",
    title: "Results published for Science Pre Test",
    timestamp: "2 hrs ago",
    type: "results",
    iconBgColor: "bg-emerald-100",
    iconColor: "text-emerald-600",
  },
  {
    id: "act-5",
    title: "Student profile updated",
    timestamp: "3 hrs ago",
    type: "update",
    iconBgColor: "bg-purple-100",
    iconColor: "text-purple-600",
  },
];

export const mockUpcomingExams: UpcomingExam[] = [
  {
    id: "exam-1",
    name: "National Science Olympiad (NSO)",
    code: "NSO",
    examDate: "18 Aug 2026",
    duration: "2 hrs",
    registeredCount: 186,
    capacityCount: 214,
    status: "Open",
    registrationEndsDate: "10 Aug 2026",
  },
  {
    id: "exam-2",
    name: "Mathematics Olympiad (IMO)",
    code: "IMO",
    examDate: "24 Aug 2026",
    duration: "1.5 hrs",
    registeredCount: 172,
    capacityCount: 200,
    status: "Open",
    registrationEndsDate: "16 Aug 2026",
  },
  {
    id: "exam-3",
    name: "English Assessment Test",
    code: "EAT",
    examDate: "02 Sep 2026",
    duration: "1 hr",
    registeredCount: 145,
    capacityCount: 180,
    status: "Upcoming",
    registrationEndsDate: "25 Aug 2026",
  },
];
