export interface PracticeTestItem {
  id: number;
  testNumber: number;
  title: string;
  topic: string;
  questionsCount: number;
  durationMinutes: number;
  difficulty: "Easy" | "Medium" | "Hard";
  isCompleted: boolean;
  score?: number;
  maxScore?: number;
}

export const SUBJECT_PRACTICE_TESTS_MAP: Record<string, PracticeTestItem[]> = {
  science: [
    {
      id: 1,
      testNumber: 1,
      title: "Physical Quantities and Measurements",
      topic: "Measurements",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Easy",
      isCompleted: true,
      score: 72,
      maxScore: 100,
    },
    {
      id: 2,
      testNumber: 2,
      title: "Motion and Force",
      topic: "Force and Motion",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Easy",
      isCompleted: true,
      score: 78,
      maxScore: 100,
    },
    {
      id: 3,
      testNumber: 3,
      title: "Work, Energy and Power",
      topic: "Work and Energy",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Medium",
      isCompleted: true,
      score: 64,
      maxScore: 100,
    },
    {
      id: 4,
      testNumber: 4,
      title: "Sound",
      topic: "Waves",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Medium",
      isCompleted: true,
      score: 70,
      maxScore: 100,
    },
    {
      id: 5,
      testNumber: 5,
      title: "Light – Reflection and Refraction",
      topic: "Light",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Medium",
      isCompleted: true,
      score: 68,
      maxScore: 100,
    },
    {
      id: 6,
      testNumber: 6,
      title: "Human Body – Nutrition and Health",
      topic: "Life Processes",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Easy",
      isCompleted: true,
      score: 74,
      maxScore: 100,
    },
    {
      id: 7,
      testNumber: 7,
      title: "Respiration in Organisms",
      topic: "Life Processes",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Medium",
      isCompleted: false,
    },
    {
      id: 8,
      testNumber: 8,
      title: "Chemical Reactions and Equations",
      topic: "Chemical Reactions",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Medium",
      isCompleted: false,
    },
    {
      id: 9,
      testNumber: 9,
      title: "Acids, Bases and Salts",
      topic: "Acids, Bases and Salts",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Easy",
      isCompleted: false,
    },
    {
      id: 10,
      testNumber: 10,
      title: "Environmental Management",
      topic: "Our Environment",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Easy",
      isCompleted: false,
    },
  ],
  math: [
    {
      id: 1,
      testNumber: 1,
      title: "Rational Numbers and Exponents",
      topic: "Number Systems",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Easy",
      isCompleted: true,
      score: 82,
      maxScore: 100,
    },
    {
      id: 2,
      testNumber: 2,
      title: "Linear Equations in One Variable",
      topic: "Algebra",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Easy",
      isCompleted: true,
      score: 76,
      maxScore: 100,
    },
    {
      id: 3,
      testNumber: 3,
      title: "Understanding Quadrilaterals",
      topic: "Geometry",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Medium",
      isCompleted: true,
      score: 70,
      maxScore: 100,
    },
    {
      id: 4,
      testNumber: 4,
      title: "Data Handling and Probability",
      topic: "Statistics",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Easy",
      isCompleted: true,
      score: 85,
      maxScore: 100,
    },
    {
      id: 5,
      testNumber: 5,
      title: "Squares, Square Roots & Cubes",
      topic: "Number Operations",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Medium",
      isCompleted: true,
      score: 68,
      maxScore: 100,
    },
    {
      id: 6,
      testNumber: 6,
      title: "Comparing Quantities & Percentages",
      topic: "Commercial Math",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Medium",
      isCompleted: true,
      score: 72,
      maxScore: 100,
    },
    {
      id: 7,
      testNumber: 7,
      title: "Algebraic Expressions & Identities",
      topic: "Algebra",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Medium",
      isCompleted: true,
      score: 74,
      maxScore: 100,
    },
    {
      id: 8,
      testNumber: 8,
      title: "Mensuration & Area of Polygons",
      topic: "Geometry",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Hard",
      isCompleted: true,
      score: 65,
      maxScore: 100,
    },
    {
      id: 9,
      testNumber: 9,
      title: "Direct and Inverse Proportions",
      topic: "Ratios & Proportion",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Easy",
      isCompleted: false,
    },
    {
      id: 10,
      testNumber: 10,
      title: "Factorisation & Introduction to Graphs",
      topic: "Advanced Algebra",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Medium",
      isCompleted: false,
    },
  ],
  english: [
    {
      id: 1,
      testNumber: 1,
      title: "Reading Comprehension & Inferences",
      topic: "Comprehension",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Easy",
      isCompleted: true,
      score: 80,
      maxScore: 100,
    },
    {
      id: 2,
      testNumber: 2,
      title: "Nouns, Pronouns & Subject-Verb Agreement",
      topic: "Grammar Fundamentals",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Easy",
      isCompleted: true,
      score: 84,
      maxScore: 100,
    },
    {
      id: 3,
      testNumber: 3,
      title: "Tenses & Voice Transformations",
      topic: "Grammar Advanced",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Medium",
      isCompleted: true,
      score: 70,
      maxScore: 100,
    },
    {
      id: 4,
      testNumber: 4,
      title: "Direct and Reported Speech",
      topic: "Speech & Narration",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Medium",
      isCompleted: true,
      score: 72,
      maxScore: 100,
    },
    {
      id: 5,
      testNumber: 5,
      title: "Synonyms, Antonyms & Idioms",
      topic: "Vocabulary",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Easy",
      isCompleted: false,
    },
    {
      id: 6,
      testNumber: 6,
      title: "Sentence Correction & Spotting Errors",
      topic: "Applied Grammar",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Medium",
      isCompleted: false,
    },
    {
      id: 7,
      testNumber: 7,
      title: "Cloze Test & Passage Filling",
      topic: "Comprehension",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Medium",
      isCompleted: false,
    },
    {
      id: 8,
      testNumber: 8,
      title: "Word Formation, Prefixes & Suffixes",
      topic: "Vocabulary",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Easy",
      isCompleted: false,
    },
    {
      id: 9,
      testNumber: 9,
      title: "Formal & Informal Letter Formats",
      topic: "Writing Skills",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Easy",
      isCompleted: false,
    },
    {
      id: 10,
      testNumber: 10,
      title: "National English Olympiad Grand Mock",
      topic: "Mock Exam",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Hard",
      isCompleted: false,
    },
  ],
  gk: [
    {
      id: 1,
      testNumber: 1,
      title: "Indian Heritage & Ancient Monuments",
      topic: "History",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Easy",
      isCompleted: true,
      score: 78,
      maxScore: 100,
    },
    {
      id: 2,
      testNumber: 2,
      title: "Physical Geography & River Systems",
      topic: "Geography",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Medium",
      isCompleted: true,
      score: 72,
      maxScore: 100,
    },
    {
      id: 3,
      testNumber: 3,
      title: "Indian Constitution & Fundamental Rights",
      topic: "Civics & Polity",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Medium",
      isCompleted: true,
      score: 66,
      maxScore: 100,
    },
    {
      id: 4,
      testNumber: 4,
      title: "Space Exploration, Planets & ISRO",
      topic: "Space Science",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Easy",
      isCompleted: true,
      score: 82,
      maxScore: 100,
    },
    {
      id: 5,
      testNumber: 5,
      title: "Major Inventions & Global Scientists",
      topic: "Science & Tech",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Easy",
      isCompleted: false,
    },
    {
      id: 6,
      testNumber: 6,
      title: "World Organizations (UN, WHO, UNESCO)",
      topic: "Current Affairs",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Medium",
      isCompleted: false,
    },
    {
      id: 7,
      testNumber: 7,
      title: "Olympic Games, Sports & Prestigious Awards",
      topic: "Sports & Honors",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Easy",
      isCompleted: false,
    },
    {
      id: 8,
      testNumber: 8,
      title: "Wildlife Sanctuaries, Flora & Fauna",
      topic: "Ecology & Nature",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Medium",
      isCompleted: false,
    },
    {
      id: 9,
      testNumber: 9,
      title: "Logical Riddles & Non-Verbal Puzzles",
      topic: "Logical Reasoning",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Medium",
      isCompleted: false,
    },
    {
      id: 10,
      testNumber: 10,
      title: "IQ Olympiad All-India Grand GK Mock",
      topic: "Comprehensive Mock",
      questionsCount: 50,
      durationMinutes: 50,
      difficulty: "Hard",
      isCompleted: false,
    },
  ],
};
