import { OlympiadItem, OlympiadStatCardData } from "./types";

export const initialOlympiadsData: OlympiadItem[] = [
  {
    id: "1",
    name: "International Mathematics Olympiad",
    subtitle: "World's most prestigious mathematics competition",
    code: "IMO",
    classes: "1 - 12",
    category: "Mathematics",
    categoryColor: "bg-blue-100/70 text-blue-600",
    status: "Active",
    registrations: 12450,
    avatarCode: "IMO",
    avatarBg: "bg-[#1E56A0] text-white",
  },
  {
    id: "2",
    name: "National Science Olympiad",
    subtitle: "Science talent search for school students",
    code: "NSO",
    classes: "1 - 12",
    category: "Science",
    categoryColor: "bg-emerald-100/70 text-emerald-600",
    status: "Active",
    registrations: 9872,
    avatarCode: "NSO",
    avatarBg: "bg-[#059669] text-white",
  },
  {
    id: "3",
    name: "International English Olympiad",
    subtitle: "Excellence in English language skills",
    code: "IEO",
    classes: "1 - 12",
    category: "English",
    categoryColor: "bg-amber-100/70 text-amber-600",
    status: "Active",
    registrations: 7654,
    avatarCode: "IEO",
    avatarBg: "bg-[#D97706] text-white",
  },
  {
    id: "4",
    name: "International General Knowledge Olympiad",
    subtitle: "Testing knowledge beyond the classroom",
    code: "IGKO",
    classes: "1 - 12",
    category: "General Knowledge",
    categoryColor: "bg-purple-100/70 text-purple-600",
    status: "Active",
    registrations: 10213,
    avatarCode: "IGKO",
    avatarBg: "bg-[#7C3AED] text-white",
  },
  {
    id: "5",
    name: "National Cyber Olympiad",
    subtitle: "Enhancing cybersecurity skills for the digital future",
    code: "NCO",
    classes: "8 - 12",
    category: "Cyber Security",
    categoryColor: "bg-sky-100/70 text-sky-600",
    status: "Upcoming",
    registrations: null,
    avatarCode: "NCO",
    avatarBg: "bg-[#0284C7] text-white",
    startDate: "15 Jun 2025",
    startTime: "10:00 AM",
    regEndDate: "05 Jun 2025",
    regEndTime: "11:59 PM",
  },
  {
    id: "6",
    name: "International Astronomy Olympiad",
    subtitle: "Exploring space, astrophysics and cosmos",
    code: "IAO",
    classes: "6 - 12",
    category: "Astronomy",
    categoryColor: "bg-indigo-100/70 text-indigo-600",
    status: "Upcoming",
    registrations: null,
    avatarCode: "IAO",
    avatarBg: "bg-[#4F46E5] text-white",
    startDate: "20 Jun 2025",
    startTime: "10:00 AM",
    regEndDate: "10 Jun 2025",
    regEndTime: "11:59 PM",
  },
  {
    id: "7",
    name: "International STEM Olympiad",
    subtitle: "Interdisciplinary science and technology challenge",
    code: "ISO",
    classes: "5 - 12",
    category: "Science",
    categoryColor: "bg-emerald-100/70 text-emerald-600",
    status: "Upcoming",
    registrations: null,
    avatarCode: "ISO",
    avatarBg: "bg-[#0D9488] text-white",
    startDate: "25 Jun 2025",
    startTime: "10:00 AM",
    regEndDate: "15 Jun 2025",
    regEndTime: "11:59 PM",
  },
  {
    id: "8",
    name: "Reasoning Olympiad",
    subtitle: "Logical and analytical reasoning competition",
    code: "REAS",
    classes: "1 - 12",
    category: "Reasoning",
    categoryColor: "bg-pink-100/70 text-pink-600",
    status: "Completed",
    registrations: 8341,
    avatarCode: "REAS",
    avatarBg: "bg-[#DB2777] text-white",
    completedDate: "15 May 2025",
    completedTime: "10:00 AM",
  },
  {
    id: "9",
    name: "Aptitude Skills Olympiad",
    subtitle: "Building problem solving skills for future",
    code: "ASO",
    classes: "1 - 10",
    category: "Aptitude",
    categoryColor: "bg-teal-100/70 text-teal-600",
    status: "Completed",
    registrations: 5432,
    avatarCode: "ASO",
    avatarBg: "bg-[#0D9488] text-white",
    completedDate: "20 Nov 2024",
    completedTime: "10:00 AM",
  },
];

export const statCardsData: OlympiadStatCardData[] = [
  {
    id: "all",
    title: "Total Olympiads",
    value: 24,
    subtitle: "All olympiads",
    trend: "↑ 12%",
    trendColor: "text-amber-600",
    iconBg: "bg-orange-50 border border-orange-100",
    iconColor: "text-amber-500",
    borderColor: "border-2 border-amber-500 shadow-sm ring-2 ring-amber-500/10",
    sparklineColor: "#F59E0B",
    sparklinePoints: "0,20 15,14 30,18 45,8 60,16 75,6 90,14 105,4 120,12",
  },
  {
    id: "Active",
    title: "Active Olympiads",
    value: 16,
    subtitle: "Currently active",
    trend: "↑ 8%",
    trendColor: "text-emerald-600",
    iconBg: "bg-emerald-50 border border-emerald-100",
    iconColor: "text-emerald-500",
    borderColor: "border-2 border-emerald-500 shadow-sm ring-2 ring-emerald-500/10",
    sparklineColor: "#10B981",
    sparklinePoints: "0,16 15,12 30,18 45,10 60,16 75,8 90,14 105,6 120,10",
  },
  {
    id: "Upcoming",
    title: "Upcoming Olympiads",
    value: 5,
    subtitle: "Not started yet",
    trend: "↑ 5%",
    trendColor: "text-blue-600",
    iconBg: "bg-blue-50 border border-blue-100",
    iconColor: "text-blue-500",
    borderColor: "border-2 border-blue-500 shadow-sm ring-2 ring-blue-500/10",
    sparklineColor: "#3B82F6",
    sparklinePoints: "0,18 15,15 30,12 45,16 60,10 75,14 90,8 105,12 120,6",
  },
  {
    id: "Completed",
    title: "Completed Olympiads",
    value: 8,
    subtitle: "This year",
    trend: "↑ 10%",
    trendColor: "text-purple-600",
    iconBg: "bg-purple-50 border border-purple-100",
    iconColor: "text-purple-500",
    borderColor: "border-2 border-purple-500 shadow-sm ring-2 ring-purple-500/10",
    sparklineColor: "#8B5CF6",
    sparklinePoints: "0,15 15,18 30,12 45,14 60,8 75,12 90,6 105,10 120,4",
  },
];
