import { CertificateRecord, CertificatesStatCardData } from "./types";

export const initialCertificatesData: CertificateRecord[] = [
  {
    id: "1",
    rank: 1,
    studentName: "Aarav Sharma",
    avatarInitials: "AS",
    registrationId: "IQR10001",
    rollNo: "100104",
    examName: "IMO - Mathematics",
    classNum: "10",
    score: "91.5 / 100",
    percentage: "91.50%",
    certificateType: "Merit",
    status: "Issued",
    issueDate: "12 May 2026",
  },
  {
    id: "2",
    rank: 2,
    studentName: "Siya Nair",
    avatarInitials: "SN",
    registrationId: "IQR10002",
    rollNo: "100187",
    examName: "NSO - Science",
    classNum: "10",
    score: "85 / 100",
    percentage: "85.00%",
    certificateType: "Merit",
    status: "Issued",
    issueDate: "10 May 2026",
  },
  {
    id: "3",
    rank: 3,
    studentName: "Vivaan Patel",
    avatarInitials: "VP",
    registrationId: "IQR10003",
    rollNo: "100254",
    examName: "IEO - English",
    classNum: "9",
    score: "78.5 / 100",
    percentage: "78.50%",
    certificateType: "Merit",
    status: "Issued",
    issueDate: "09 May 2026",
  },
  {
    id: "4",
    rank: 4,
    studentName: "Riya Mehta",
    avatarInitials: "RM",
    registrationId: "IQR10004",
    rollNo: "100309",
    examName: "IGKO - GK",
    classNum: "10",
    score: "72 / 100",
    percentage: "72.00%",
    certificateType: "Merit",
    status: "Issued",
    issueDate: "08 May 2026",
  },
  {
    id: "5",
    rank: 5,
    studentName: "Arjun Reddy",
    avatarInitials: "AR",
    registrationId: "IQR10005",
    rollNo: "100356",
    examName: "REAS - Reasoning",
    classNum: "8",
    score: "68.5 / 100",
    percentage: "68.50%",
    certificateType: "Merit",
    status: "Issued",
    issueDate: "07 May 2026",
  },
];

export const participationCertificatesData: CertificateRecord[] = [
  { id: "p1", rank: 1, studentName: "Aman Verma", avatarInitials: "AS", registrationId: "IQR20001", rollNo: "100234", examName: "IMO - Mathematics", classNum: "10", score: "65 / 100", percentage: "65.00%", certificateType: "Participation", status: "Issued", issueDate: "12 May 2026" },
  { id: "p2", rank: 2, studentName: "Sneha Reddy", avatarInitials: "SN", registrationId: "IQR20002", rollNo: "100198", examName: "NSO - Science", classNum: "10", score: "62 / 100", percentage: "62.00%", certificateType: "Participation", status: "Issued", issueDate: "10 May 2026" },
  { id: "p3", rank: 3, studentName: "Rohit Kumar", avatarInitials: "RK", registrationId: "IQR20003", rollNo: "100256", examName: "IEO - English", classNum: "9", score: "59 / 100", percentage: "59.00%", certificateType: "Participation", status: "Issued", issueDate: "09 May 2026" },
  { id: "p4", rank: 4, studentName: "Pooja Kulkarni", avatarInitials: "PK", registrationId: "IQR20004", rollNo: "100301", examName: "IGKO - GK", classNum: "10", score: "55 / 100", percentage: "55.00%", certificateType: "Participation", status: "Issued", issueDate: "08 May 2026" },
  { id: "p5", rank: 5, studentName: "Aditya Deshmukh", avatarInitials: "AD", registrationId: "IQR20005", rollNo: "100357", examName: "REAS - Reasoning", classNum: "8", score: "52 / 100", percentage: "52.00%", certificateType: "Participation", status: "Issued", issueDate: "07 May 2026" },
  { id: "p6", rank: 6, studentName: "Ishita Singh", avatarInitials: "IS", registrationId: "IQR20006", rollNo: "100413", examName: "IMO - Mathematics", classNum: "12", score: "50 / 100", percentage: "50.00%", certificateType: "Participation", status: "Issued", issueDate: "06 May 2026" },
  { id: "p7", rank: 7, studentName: "Manav Verma", avatarInitials: "MV", registrationId: "IQR20007", rollNo: "100472", examName: "NSO - Science", classNum: "11", score: "48 / 100", percentage: "48.00%", certificateType: "Participation", status: "Issued", issueDate: "05 May 2026" },
  { id: "p8", rank: 8, studentName: "Kavya Sharma", avatarInitials: "KS", registrationId: "IQR20008", rollNo: "100519", examName: "IEO - English", classNum: "7", score: "45 / 100", percentage: "45.00%", certificateType: "Participation", status: "Issued", issueDate: "04 May 2026" },
  { id: "p9", rank: 9, studentName: "Ankit Gupta", avatarInitials: "AG", registrationId: "IQR20009", rollNo: "100588", examName: "IGKO - GK", classNum: "9", score: "42 / 100", percentage: "42.00%", certificateType: "Participation", status: "Issued", issueDate: "03 May 2026" },
  { id: "p10", rank: 10, studentName: "Neha Rathi", avatarInitials: "NR", registrationId: "IQR20010", rollNo: "100645", examName: "REAS - Reasoning", classNum: "6", score: "40 / 100", percentage: "40.00%", certificateType: "Participation", status: "Issued", issueDate: "02 May 2026" },
];

export const pendingCertificatesData: CertificateRecord[] = [
  { id: "nd1", rank: 1, studentName: "Aarav Sharma", avatarInitials: "AS", registrationId: "IQR10001", rollNo: "100104", examName: "IMO - Mathematics", classNum: "10", score: "91.5 / 100", percentage: "91.50%", certificateType: "Merit", status: "Pending" },
  { id: "nd2", rank: 2, studentName: "Siya Nair", avatarInitials: "SN", registrationId: "IQR10002", rollNo: "100187", examName: "NSO - Science", classNum: "10", score: "85 / 100", percentage: "85.00%", certificateType: "Participation", status: "Pending" },
  { id: "nd3", rank: 3, studentName: "Vivaan Patel", avatarInitials: "VP", registrationId: "IQR10003", rollNo: "100254", examName: "IEO - English", classNum: "9", score: "78.5 / 100", percentage: "78.50%", certificateType: "Participation", status: "Pending" },
  { id: "nd4", rank: 4, studentName: "Riya Mehta", avatarInitials: "RM", registrationId: "IQR10004", rollNo: "100309", examName: "IGKO - GK", classNum: "10", score: "72 / 100", percentage: "72.00%", certificateType: "Participation", status: "Pending" },
  { id: "nd5", rank: 5, studentName: "Arjun Reddy", avatarInitials: "AR", registrationId: "IQR10005", rollNo: "100356", examName: "REAS - Reasoning", classNum: "8", score: "68.5 / 100", percentage: "68.50%", certificateType: "Participation", status: "Pending" },
  { id: "nd6", rank: 6, studentName: "Ishaan Singh", avatarInitials: "IS", registrationId: "IQR10006", rollNo: "100412", examName: "IMO - Mathematics", classNum: "12", score: "63 / 100", percentage: "63.00%", certificateType: "Participation", status: "Pending" },
  { id: "nd7", rank: 7, studentName: "Rohan Verma", avatarInitials: "RV", registrationId: "IQR10007", rollNo: "100489", examName: "NSO - Science", classNum: "11", score: "58 / 100", percentage: "58.00%", certificateType: "Participation", status: "Pending" },
  { id: "nd8", rank: 8, studentName: "Meera Yadav", avatarInitials: "MY", registrationId: "IQR10008", rollNo: "100563", examName: "IGKO - GK", classNum: "9", score: "54 / 100", percentage: "54.00%", certificateType: "Participation", status: "Pending" },
  { id: "nd9", rank: 9, studentName: "Kabir Agarwal", avatarInitials: "KA", registrationId: "IQR10009", rollNo: "100612", examName: "IEO - English", classNum: "7", score: "49 / 100", percentage: "49.00%", certificateType: "Participation", status: "Pending" },
  { id: "nd10", rank: 10, studentName: "Pooja Rao", avatarInitials: "PR", registrationId: "IQR10010", rollNo: "100678", examName: "REAS - Reasoning", classNum: "6", score: "48 / 100", percentage: "48.00%", certificateType: "Participation", status: "Pending" },
];

export const totalCertificatesData: CertificateRecord[] = [
  { id: "t1", rank: 1, studentName: "Aarav Sharma", avatarInitials: "AS", registrationId: "IQR10001", rollNo: "100104", examName: "IMO - Mathematics", classNum: "10", score: "91.5 / 100", percentage: "91.50%", certificateType: "Merit", status: "Issued", issueDate: "12 May 2026" },
  { id: "t2", rank: 2, studentName: "Siya Nair", avatarInitials: "SN", registrationId: "IQR10002", rollNo: "100187", examName: "NSO - Science", classNum: "10", score: "85 / 100", percentage: "85.00%", certificateType: "Participation", status: "Issued", issueDate: "10 May 2026" },
  { id: "t3", rank: 3, studentName: "Vivaan Patel", avatarInitials: "VP", registrationId: "IQR10003", rollNo: "100254", examName: "IEO - English", classNum: "9", score: "78.5 / 100", percentage: "78.50%", certificateType: "Merit", status: "Issued", issueDate: "09 May 2026" },
  { id: "t4", rank: 4, studentName: "Riya Mehta", avatarInitials: "RM", registrationId: "IQR10004", rollNo: "100309", examName: "IGKO - GK", classNum: "10", score: "72 / 100", percentage: "72.00%", certificateType: "Participation", status: "Issued", issueDate: "08 May 2026" },
  { id: "t5", rank: 5, studentName: "Arjun Reddy", avatarInitials: "AR", registrationId: "IQR10005", rollNo: "100356", examName: "REAS - Reasoning", classNum: "8", score: "68.5 / 100", percentage: "68.50%", certificateType: "Participation", status: "Issued", issueDate: "07 May 2026" },
  { id: "t6", rank: 6, studentName: "Ishaan Singh", avatarInitials: "IS", registrationId: "IQR10006", rollNo: "100412", examName: "IMO - Mathematics", classNum: "12", score: "63 / 100", percentage: "63.00%", certificateType: "Merit", status: "Issued", issueDate: "06 May 2026" },
  { id: "t7", rank: 7, studentName: "Rohan Verma", avatarInitials: "RV", registrationId: "IQR10007", rollNo: "100489", examName: "NSO - Science", classNum: "11", score: "58 / 100", percentage: "58.00%", certificateType: "Participation", status: "Issued", issueDate: "05 May 2026" },
  { id: "t8", rank: 8, studentName: "Meera Yadav", avatarInitials: "MY", registrationId: "IQR10008", rollNo: "100563", examName: "IGKO - GK", classNum: "9", score: "54 / 100", percentage: "54.00%", certificateType: "Merit", status: "Issued", issueDate: "04 May 2026" },
  { id: "t9", rank: 9, studentName: "Kabir Agarwal", avatarInitials: "KA", registrationId: "IQR10009", rollNo: "100612", examName: "IEO - English", classNum: "7", score: "49 / 100", percentage: "49.00%", certificateType: "Participation", status: "Issued", issueDate: "03 May 2026" },
  { id: "t10", rank: 10, studentName: "Pooja Rao", avatarInitials: "PR", registrationId: "IQR10010", rollNo: "100678", examName: "REAS - Reasoning", classNum: "6", score: "48 / 100", percentage: "48.00%", certificateType: "Participation", status: "Issued", issueDate: "02 May 2026" },
];

export const certificatesStatCardsData: CertificatesStatCardData[] = [
  { id: "merit", title: "Merit Certificates Issued", value: "4,256", subtitle: "Issued to top performers", iconBg: "bg-purple-100/80", iconColor: "text-purple-600" },
  { id: "participation", title: "Participation Certificates Issued", value: "12,845", subtitle: "Issued to participants", iconBg: "bg-emerald-100/80", iconColor: "text-emerald-600" },
  { id: "pending", title: "Pending Certificates", value: "1,641", subtitle: "Yet to be issued", iconBg: "bg-amber-100/80", iconColor: "text-amber-600" },
  { id: "total", title: "Total Certificates Issued", value: "17,101", subtitle: "Across all types", iconBg: "bg-blue-100/80", iconColor: "text-blue-600" },
];
