import {
  StatMetric,
  PerformanceTrendPoint,
  DonutCategory,
  ReportItem,
  MeritStudentItem,
} from "./types";

export const STAT_METRICS: StatMetric[] = [
  {
    id: "appeared",
    title: "Appeared Students",
    value: "1,624",
    subtext: "Across all exams",
    iconType: "appeared",
  },
  {
    id: "qualified",
    title: "Qualified Students",
    value: "1,418",
    subtext: "87.3% qualification rate",
    badge: "87.3%",
    iconType: "qualified",
  },
  {
    id: "avg",
    title: "Avg Students Score",
    value: "78.6%",
    subtext: "Across all exams",
    iconType: "avg",
  },
  {
    id: "merit",
    title: "Merit Student",
    value: "Aarav Sharma",
    subtext: "98.5% in NSO",
    iconType: "merit",
  },
];

export const PERFORMANCE_TRENDS: PerformanceTrendPoint[] = [
  { month: "Apr '25", passPercentage: 74, averageScore: 48 },
  { month: "May '25", passPercentage: 76, averageScore: 53 },
  { month: "Jun '25", passPercentage: 66, averageScore: 44 },
  { month: "Jul '25", passPercentage: 69, averageScore: 47 },
  { month: "Aug '25", passPercentage: 77, averageScore: 56 },
  { month: "Sep '25", passPercentage: 92, averageScore: 71 },
  { month: "Oct '25", passPercentage: 99, averageScore: 76 },
  { month: "Nov '25", passPercentage: 96, averageScore: 72 },
  { month: "Dec '25", passPercentage: 81, averageScore: 57 },
  { month: "Jan '26", passPercentage: 64, averageScore: 41 },
  { month: "Feb '26", passPercentage: 79, averageScore: 54 },
  { month: "Mar '26", passPercentage: 86, averageScore: 61 },
];

export const DONUT_CATEGORIES: DonutCategory[] = [
  { name: "Exam-wise Reports", count: 18, percentage: 37.5, color: "#7c3aed" },
  { name: "Class-wise Reports", count: 12, percentage: 25.0, color: "#10b981" },
  { name: "Student-wise Reports", count: 10, percentage: 20.8, color: "#f59e0b" },
  { name: "Subject-wise Reports", count: 8, percentage: 16.7, color: "#f97316" },
];

export const RECENT_REPORTS: ReportItem[] = [
  {
    id: "rep-1",
    name: "National Science Olympiad (NSO) Report",
    type: "Exam-wise",
    examOrClass: "NSO - 2026",
    generatedOn: "28 May 2026, 10:33 AM",
    generatedBy: "Admin",
    fileSize: "2.4 MB",
  },
  {
    id: "rep-2",
    name: "Class 10 Comprehensive Report",
    type: "Class-wise",
    examOrClass: "Class 10",
    generatedOn: "27 May 2026, 04:15 PM",
    generatedBy: "Admin",
    fileSize: "4.1 MB",
  },
  {
    id: "rep-3",
    name: "IMO Mathematics Olympiad Report",
    type: "Exam-wise",
    examOrClass: "IMO - 2026",
    generatedOn: "27 May 2026, 11:20 AM",
    generatedBy: "Admin",
    fileSize: "3.2 MB",
  },
];

export const MERIT_STUDENTS_LIST: MeritStudentItem[] = [
  {
    id: "merit-1",
    rank: 1,
    studentName: "Aarav Sharma",
    class: "IX",
    examName: "National Science Olympiad",
    scorePercentage: 98.33,
    marksObtained: 59,
    totalMarks: 60,
    publishedOn: "16 May 2025",
  },
  {
    id: "merit-2",
    rank: 2,
    studentName: "Siya Patel",
    class: "VIII",
    examName: "IMO Mathematics Olympiad",
    scorePercentage: 93.33,
    marksObtained: 56,
    totalMarks: 60,
    publishedOn: "16 May 2025",
  },
  {
    id: "merit-3",
    rank: 3,
    studentName: "Rahul Verma",
    class: "X",
    examName: "Cyber Olympiad",
    scorePercentage: 91.67,
    marksObtained: 55,
    totalMarks: 60,
    publishedOn: "15 May 2025",
  },
  {
    id: "merit-4",
    rank: 4,
    studentName: "Ananya Joshi",
    class: "VII",
    examName: "English Olympiad",
    scorePercentage: 90.0,
    marksObtained: 54,
    totalMarks: 60,
    publishedOn: "15 May 2025",
  },
  {
    id: "merit-5",
    rank: 5,
    studentName: "Vivaan Mehta",
    class: "IX",
    examName: "AI Olympiad",
    scorePercentage: 88.33,
    marksObtained: 53,
    totalMarks: 60,
    publishedOn: "14 May 2025",
  },
  {
    id: "merit-6",
    rank: 6,
    studentName: "Ishita Rao",
    class: "VIII",
    examName: "National Science Olympiad",
    scorePercentage: 87.0,
    marksObtained: 52,
    totalMarks: 60,
    publishedOn: "14 May 2025",
  },
  {
    id: "merit-7",
    rank: 7,
    studentName: "Arjun Nair",
    class: "X",
    examName: "IMO Mathematics Olympiad",
    scorePercentage: 86.67,
    marksObtained: 52,
    totalMarks: 60,
    publishedOn: "14 May 2025",
  },
  {
    id: "merit-8",
    rank: 8,
    studentName: "Meera Kapoor",
    class: "VI",
    examName: "Cyber Olympiad",
    scorePercentage: 85.0,
    marksObtained: 51,
    totalMarks: 60,
    publishedOn: "13 May 2025",
  },
  {
    id: "merit-9",
    rank: 9,
    studentName: "Kabir Singh",
    class: "IX",
    examName: "English Olympiad",
    scorePercentage: 84.17,
    marksObtained: 50,
    totalMarks: 60,
    publishedOn: "13 May 2025",
  },
  {
    id: "merit-10",
    rank: 10,
    studentName: "Riya Gupta",
    class: "VIII",
    examName: "AI Olympiad",
    scorePercentage: 83.33,
    marksObtained: 50,
    totalMarks: 60,
    publishedOn: "13 May 2025",
  },
];
