"use client";

import React, { useState } from "react";
import { Eye, Download, FileText, ChevronLeft, ChevronRight, CheckCircle2, Clock } from "lucide-react";
import { ReportItem } from "./types";

interface RecentReportsTableProps {
  reports: ReportItem[];
  totalCount: number;
  onPreview: (report: ReportItem) => void;
  onDownload: (report: ReportItem) => void;
}

export const RecentReportsTable: React.FC<RecentReportsTableProps> = ({
  reports,
  totalCount,
  onPreview,
  onDownload,
}) => {
  const [currentPage, setCurrentPage] = useState(1);

  const getReportIcon = (type: ReportItem["type"]) => {
    switch (type) {
      case "Exam-wise":
        return <FileText className="w-4.5 h-4.5 text-purple-600" />;
      case "Class-wise":
        return <CheckCircle2 className="w-4.5 h-4.5 text-emerald-500" />;
      case "Student-wise":
        return <Clock className="w-4.5 h-4.5 text-amber-500" />;
      default:
        return <FileText className="w-4.5 h-4.5 text-orange-500" />;
    }
  };

  const getIconBg = (type: ReportItem["type"]) => {
    switch (type) {
      case "Exam-wise":
        return "bg-purple-100/70";
      case "Class-wise":
        return "bg-emerald-100/70";
      case "Student-wise":
        return "bg-amber-100/70";
      default:
        return "bg-orange-100/70";
    }
  };

  return (
    <div className="bg-white rounded-3xl p-6 border border-slate-100/90 shadow-2xs space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-black text-slate-900 tracking-tight">Recent Reports</h3>
        <button className="text-sm font-extrabold text-[#7c3aed] hover:underline cursor-pointer">
          View All
        </button>
      </div>

      {/* Table */}
      <div className="overflow-x-auto">
        <table className="w-full text-left border-collapse min-w-[680px]">
          <thead>
            <tr className="border-b border-slate-200/80 text-xs font-extrabold text-slate-500 uppercase tracking-wider">
              <th className="py-3 px-3">REPORT NAME</th>
              <th className="py-3 px-3">TYPE</th>
              <th className="py-3 px-3">EXAM / CLASS</th>
              <th className="py-3 px-3">GENERATED ON</th>
              <th className="py-3 px-3">GENERATED BY</th>
              <th className="py-3 px-3 text-right">ACTION</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100 text-xs sm:text-sm font-medium text-slate-700">
            {reports.slice(0, 3).map((report) => (
              <tr key={report.id} className="hover:bg-slate-50/70 transition-colors">
                <td className="py-4 px-3">
                  <div className="flex items-center gap-3">
                    <div
                      className={`w-9 h-9 rounded-full flex items-center justify-center flex-shrink-0 ${getIconBg(
                        report.type
                      )}`}
                    >
                      {getReportIcon(report.type)}
                    </div>
                    <span className="font-bold text-sm text-[#3b82f6] hover:underline cursor-pointer">
                      {report.name}
                    </span>
                  </div>
                </td>
                <td className="py-4 px-3 text-slate-600 font-semibold">{report.type}</td>
                <td className="py-4 px-3 font-extrabold text-slate-900">{report.examOrClass}</td>
                <td className="py-4 px-3 text-slate-600 font-medium">{report.generatedOn}</td>
                <td className="py-4 px-3 text-slate-600 font-medium">{report.generatedBy}</td>
                <td className="py-4 px-3 text-right">
                  <div className="flex items-center justify-end gap-3 text-slate-500">
                    <button
                      onClick={() => onPreview(report)}
                      title="Preview"
                      className="p-1.5 hover:text-purple-600 transition cursor-pointer"
                    >
                      <Eye className="w-5 h-5" />
                    </button>
                    <button
                      onClick={() => onDownload(report)}
                      title="Download"
                      className="p-1.5 hover:text-purple-600 transition cursor-pointer"
                    >
                      <Download className="w-5 h-5" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Pagination Footer */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-3 pt-3 border-t border-slate-100 text-xs sm:text-sm">
        <p className="text-slate-500 font-semibold">
          Showing 1 to 3 of <span className="font-bold text-slate-900">48</span> reports
        </p>

        <div className="flex items-center gap-1.5">
          <button
            disabled={currentPage === 1}
            onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
            className="w-9 h-9 rounded-xl border border-slate-200 flex items-center justify-center text-slate-500 hover:bg-slate-50 transition cursor-pointer"
          >
            <ChevronLeft className="w-4.5 h-4.5" />
          </button>

          {[1, 2, 3].map((page) => (
            <button
              key={page}
              onClick={() => setCurrentPage(page)}
              className={`w-9 h-9 rounded-xl font-bold text-sm transition cursor-pointer ${currentPage === page
                  ? "bg-[#7c3aed] text-white shadow-2xs"
                  : "border border-slate-200 text-slate-700 hover:bg-slate-50"
                }`}
            >
              {page}
            </button>
          ))}

          <span className="px-1 text-slate-400 font-medium">...</span>

          <button
            onClick={() => setCurrentPage(16)}
            className="w-9 h-9 rounded-xl border border-slate-200 text-slate-700 font-bold text-sm hover:bg-slate-50 transition cursor-pointer"
          >
            16
          </button>

          <button
            onClick={() => setCurrentPage((p) => Math.min(16, p + 1))}
            className="w-9 h-9 rounded-xl border border-slate-200 flex items-center justify-center text-slate-500 hover:bg-slate-50 transition cursor-pointer"
          >
            <ChevronRight className="w-4.5 h-4.5" />
          </button>
        </div>
      </div>
    </div>
  );
};
