import { OlympiadItem, BenefitFeature } from "./types";

export const OLYMPIADS_DATA: OlympiadItem[] = [
  // --- LIVE OLYMPIADS ---
  {
    id: "intelliquest-2026",
    slug: "intelliquest-2026",
    name: "IntelliQuest 2025",
    tagline: "The Grand Intellectual Challenge",
    iconType: "brain",
    isFlagship: true,
    subjects: ["All Subjects", "Classes 7 - 12"],
    primarySubject: "All Subjects",
    eligibility: "Classes 7 - 12",
    examDate: "Mar 15, 2026",
    duration: "2 Hours",
    difficulty: "Moderate to High",
    description: "India's most prestigious inter-school olympiad to identify and nurture future leaders.",
    status: "Live",
    hasPrizes: true,
  },
  {
    id: "imo",
    slug: "imo",
    name: "IMO",
    tagline: "International Mathematics Olympiad",
    iconType: "sigma",
    subjects: ["Mathematics", "Classes 7 - 12"],
    primarySubject: "Mathematics",
    eligibility: "Classes 7 - 12",
    examDate: "Nov 16, 2025",
    duration: "2 Hours",
    difficulty: "Challenging",
    description: "Test your problem-solving skills and mathematical reasoning in this global competition.",
    status: "Live",
    hasPrizes: false,
    customIconBg: "bg-blue-100 text-blue-600",
  },
  {
    id: "nso",
    slug: "nso",
    name: "NSO",
    tagline: "National Science Olympiad",
    iconType: "flask",
    subjects: ["Science", "Classes 7 - 12"],
    primarySubject: "Science",
    eligibility: "Classes 7 - 12",
    examDate: "Dec 07, 2025",
    duration: "1.5 Hours",
    difficulty: "Moderate",
    description: "Explore the wonders of science and test conceptual understanding with real-world applications.",
    status: "Live",
    hasPrizes: false,
    customIconBg: "bg-emerald-100 text-emerald-600",
  },

  // --- UPCOMING OLYMPIADS ---
  {
    id: "ieo",
    slug: "ieo",
    name: "IEO",
    tagline: "International English Olympiad",
    iconType: "book",
    subjects: ["English", "Classes 7 - 12"],
    primarySubject: "English",
    eligibility: "Classes 7 - 12",
    examDate: "Dec 14, 2025",
    duration: "1.5 Hours",
    difficulty: "Moderate",
    description: "Enhance your language skills, vocabulary and analytical thinking through engaging questions.",
    status: "Upcoming",
    hasPrizes: false,
    customIconBg: "bg-pink-100 text-pink-600",
  },
  {
    id: "nco",
    slug: "nco",
    name: "NCO",
    tagline: "National Cyber Olympiad",
    iconType: "cyber",
    subjects: ["Reasoning", "Classes 7 - 12"],
    primarySubject: "Reasoning",
    eligibility: "Classes 7 - 12",
    examDate: "Jan 18, 2026",
    duration: "1.5 Hours",
    difficulty: "Moderate",
    description: "Sharpen logical reasoning and cyber problem-solving skills with challenging questions.",
    status: "Upcoming",
    hasPrizes: false,
    customIconBg: "bg-purple-100 text-purple-600",
  },
  {
    id: "ai-olympiad",
    slug: "ai-olympiad",
    name: "AI Olympiad",
    tagline: "Future Ready with AI",
    iconType: "ai",
    subjects: ["AI", "Classes 8 - 12"],
    primarySubject: "AI",
    eligibility: "Classes 8 - 12",
    examDate: "Feb 08, 2026",
    duration: "2 Hours",
    difficulty: "Challenging",
    description: "Explore artificial intelligence fundamentals and test skills in next-generation technologies.",
    status: "Upcoming",
    hasPrizes: true,
    customIconBg: "bg-purple-100 text-purple-600",
  },

  // --- COMPLETED OLYMPIADS ---
  {
    id: "intelliquest-2024",
    slug: "intelliquest-2026",
    name: "IntelliQuest 2024",
    tagline: "The Grand Intellectual Challenge",
    iconType: "brain",
    isFlagship: true,
    subjects: ["All Subjects", "Classes 7 - 12"],
    primarySubject: "All Subjects",
    eligibility: "Classes 7 - 12",
    examDate: "Mar 10, 2025",
    duration: "2 Hours",
    difficulty: "Moderate to High",
    description: "Over 50,000 students competed nationwide. Final scores and rank certificates are released.",
    status: "Completed",
    hasPrizes: true,
  },
  {
    id: "nso-2024",
    slug: "nso",
    name: "NSO 2024",
    tagline: "National Science Olympiad",
    iconType: "flask",
    subjects: ["Science", "Classes 7 - 12"],
    primarySubject: "Science",
    eligibility: "Classes 7 - 12",
    examDate: "Dec 10, 2024",
    duration: "1.5 Hours",
    difficulty: "Moderate",
    description: "Celebrated young scientific minds across 2,000+ schools. Merit certificates released.",
    status: "Completed",
    hasPrizes: false,
    customIconBg: "bg-emerald-100 text-emerald-600",
  },
];

export const WHY_PARTICIPATE_BENEFITS: BenefitFeature[] = [
  {
    title: "Why Participate?",
    description: "More than just an exam — it's a step towards your bigger dreams.",
    iconName: "target",
  },
  {
    title: "Certificates",
    description: "Get recognized for your hard work and achievement.",
    iconName: "certificate",
  },
  {
    title: "National Ranking",
    description: "See how you rank among thousands of talented students.",
    iconName: "ranking",
  },
  {
    title: "Scholarships & Prizes",
    description: "Win exciting prizes and scholarships for top performers.",
    iconName: "scholarship",
  },
  {
    title: "Skill Development",
    description: "Build confidence, improve problem-solving and critical thinking.",
    iconName: "skill",
  },
];
